### PR TITLE
Torrents don't crash if api is down

### PR DESCRIPTION
**Pull request by PrajwalS3**

### CODE REVIEW

**Comment by FrosT2k5** [comment]
@PrajwalS3 Wow

**Comment by FrosT2k5** [comment]
@FrosT2k5 Fek I didn't wanted to do dis

**Comment by FrosT2k5** [comment]
@PrajwalS3 Why did u just replace the file tho lmao

**Comment by nnippon** [comment]
@FrosT2k5 lol

**Pull request closed without merging**
